
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "public-cloud-databases-operator.fullname" . }}
  namespace: {{ .Values.namespace }}

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "public-cloud-databases-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "public-cloud-databases-operator.fullname" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "public-cloud-databases-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "public-cloud-databases-operator.fullname" . }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - nodes
    verbs:
      - '*'


  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'

  - apiGroups:
      - service.clouddatabases.ovhcloud.net
    resources:
      - service
    verbs:
      - '*'


  - apiGroups:
      - service.clouddatabases.ovhcloud.net
    resources:
      - service/finalizers
    verbs:
      - update
