apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials
  namespace:  {{ .Values.namespace }}

type: Opaque
data:
  region: {{ .Values.region | b64enc  }}
  applicationKey: {{  .Values.applicationKey | b64enc  }}
  applicationSecret: {{ .Values.applicationSecret | b64enc  }}
  consumerKey: {{  .Values.consumerKey | b64enc  }}