{{- if not .Values.ovhCredentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: credentials
    app.kubernetes.io/created-by: public-cloud-databases-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: secret
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/part-of: public-cloud-databases-operator
  name: {{ include "ovhcreds.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  region: {{ .Values.ovhCredentials.region | b64enc }}
  applicationKey: {{ .Values.ovhCredentials.applicationKey | b64enc }}
  applicationSecret: {{ .Values.ovhCredentials.applicationSecret | b64enc }}
  consumerKey: {{ .Values.ovhCredentials.consumerKey | b64enc }}
{{- end }}
