apiVersion: v2
name: public-cloud-databases-operator
description: OVHcloud databases operator
type: application

version: 0.1.10
appVersion: "v1.1.0"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
