apiVersion: v2
name: public-cloud-databases-operator
description: OVHcloud databases operator
type: application

version: 0.1.8
appVersion: "v1.0.7"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
