apiVersion: v2
name: public-cloud-databases-operator
description: OVHcloud databases operator
type: application

version: 0.1.9
appVersion: "v1.0.8"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
